export interface IcourseDetails {
  id:number;
  categoryName:string;
  subcatName:string;
  topicName:string;
  courseTitle:string;
  courseDisc:string;
  rating:number;
  numStudent:number;
  instractor:string;
  LastUpdate:Date;
  videoUrl:string;
  price:number;
  Objectives:[{id:number,content:string}];//8
  totalsection:number;
  totallecture:number;
  totalhours:number;
  totalmin:number;
  Requerments:[{id:number,content:string}];
  Description:string;
  imgReviewer:string;
  ReviewerName:string;
  NumberOfCourse:number;
  NumberOfReview:number;
  reviewDate:Date;
  review:string;
  numstudent:number;
  totalReview:number;
  instractorRating:number;
  instCourseNum:number;
  instDecription:string;
  instImg:string;
  instWork:string;
  instlink:string
}
